import type { Metadata } from "next";
import SectionIntro from "@/components/SectionIntro";

export const metadata: Metadata = {
  title: "รู้จักภูฏาน",
  description: "ทำความรู้จักประเทศภูฏาน เมืองพาโร ทิมพู พูนาคา ฤดูกาล วัฒนธรรม และแนวคิดความสุข โดย Bhutan Center",
  alternates: { canonical: "https://www.bhutancenter.org/bhutan" },
  robots: { index: true, follow: true },
};

export default function AboutBhutanPage(){return <>
  <section className="page-hero"><div className="container"><span className="breadcrumbs">Discover / Bhutan</span><h1>ทำความรู้จัก<br/>ราชอาณาจักรภูฏาน</h1><p>ดินแดนบนเทือกเขาหิมาลัยที่มีชื่อในภาษาท้องถิ่นว่า Druk Yul — ดินแดนแห่งมังกรสายฟ้า</p></div></section>
  <section className="section"><div className="container"><SectionIntro eyebrow="Bhutan at a glance" title="ประเทศเล็กที่มีเอกลักษณ์ชัดเจน"/><div className="content-grid"><div className="info-card"><h3>ภูมิประเทศ</h3><p>ภูฏานตั้งอยู่ระหว่างอินเดียและจีนในแนวเทือกเขาหิมาลัย ไม่มีทางออกทะเล และมีภูมิประเทศตั้งแต่พื้นที่ต่ำไปจนถึงภูเขาสูง</p></div><div className="info-card"><h3>Druk Yul</h3><p>ชื่อท้องถิ่นของประเทศหมายถึง “ดินแดนแห่งมังกรสายฟ้า” สะท้อนอัตลักษณ์ทางวัฒนธรรมและศาสนาของภูฏาน</p></div><div className="info-card"><h3>Gross National Happiness</h3><p>ภูฏานเป็นที่รู้จักจากแนวคิดการพัฒนาที่ให้ความสำคัญกับความสุขและคุณภาพชีวิตควบคู่กับเศรษฐกิจ</p></div></div></div></section>
  <section className="section section--white"><div className="container"><SectionIntro eyebrow="Seasons" title="เที่ยวภูฏานได้ตลอดปี"/><div className="content-grid"><div className="info-card"><h3>Spring · มี.ค.–พ.ค.</h3><p>อากาศอบอุ่น ดอกไม้และธรรมชาติสดใส เหมาะกับการเดินทางและกิจกรรมกลางแจ้ง</p></div><div className="info-card"><h3>Summer · มิ.ย.–ส.ค.</h3><p>ภูเขาเขียวชอุ่ม มีฝนเป็นบางช่วง บรรยากาศสดและผู้เดินทางไม่หนาแน่นเท่าช่วงไฮซีซัน</p></div><div className="info-card"><h3>Autumn · ก.ย.–พ.ย.</h3><p>อากาศเย็น ท้องฟ้าค่อนข้างแจ่มใส เป็นหนึ่งในช่วงยอดนิยมของการเดินทางภูฏาน</p></div><div className="info-card"><h3>Winter · ธ.ค.–ก.พ.</h3><p>อากาศเย็นมากขึ้น โดยเฉพาะช่วงเช้าและค่ำ เหมาะกับผู้ที่ชอบอากาศหนาวและท้องฟ้าใส</p></div></div></div></section>
  <section className="section"><div className="container"><SectionIntro eyebrow="Key destinations" title="3 เมืองหลักของเส้นทางยอดนิยม"/><div className="destination-grid"><div id="paro" className="destination-card"><img src="https://upload.wikimedia.org/wikipedia/commons/0/0c/Paro_Taktsang%2C_Taktsang_Palphug_Monastery%2C_Tiger%27s_Nest_-views_from_the_trekking_path-_during_LGFC_-_Bhutan_2019_%28210%29.jpg" alt="Paro"/><div className="destination-caption"><small>Paro</small><h3>พาโร</h3><p>บ้านของวัดทักซัง สนามบินนานาชาติ และหุบเขาที่งดงามที่สุดแห่งหนึ่ง</p></div></div><div id="punakha" className="destination-card"><img src="https://upload.wikimedia.org/wikipedia/commons/5/58/Punakha_dzong.jpg" alt="Punakha"/><div className="destination-caption"><small>Punakha</small><h3>พูนาคา</h3><p>อดีตเมืองหลวงและที่ตั้งของ Punakha Dzong บริเวณจุดบรรจบของแม่น้ำสองสาย</p></div></div><div id="thimphu" className="destination-card"><img src="https://upload.wikimedia.org/wikipedia/commons/7/76/Tashichho_Dzong%2C_Bhutan_19.jpg" alt="Thimphu"/><div className="destination-caption"><small>Thimphu</small><h3>ทิมพู</h3><p>เมืองหลวงที่รวมวัฒนธรรม ประวัติศาสตร์ และชีวิตร่วมสมัยของภูฏานไว้ด้วยกัน</p></div></div></div></div></section>
</>}
